# Generated by Django 5.2.5 on 2025-08-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwordpolicy_securitysettings_usersecurityprofile_and_more'),
        ('authentication', '0002_security_models'),
    ]

    operations = [
    ]
