# Generated by Django 4.2.7 on 2025-08-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_remove_cie10mexico_edad_maxima_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacienteCIE10",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_diagnostico",
                    models.DateField(
                        help_text="Fecha cuando se diagnosticó este código específico",
                        verbose_name="Fecha de Diagnóstico",
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el diagnóstico principal",
                        verbose_name="Diagnóstico Principal",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre este diagnóstico",
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "cie10",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.cie10mexico",
                        verbose_name="Código CIE-10",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "CIE-10 del Paciente",
                "verbose_name_plural": "CIE-10 de los Pacientes",
                "ordering": ["-es_principal", "-fecha_diagnostico"],
                "unique_together": {("paciente", "cie10")},
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="cie10_codes",
            field=models.ManyToManyField(
                help_text="Múltiples códigos CIE-10 para el paciente",
                related_name="pacientes",
                through="patients.PacienteCIE10",
                to="patients.cie10mexico",
                verbose_name="Códigos CIE-10",
            ),
        ),
    ]
