# Generated by Django 4.2.7 on 2025-08-17 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovementTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Plantilla"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Creación"),
                            ("UPDATE", "Actualización"),
                            ("DELETE", "Eliminación"),
                            ("LOGIN", "Inicio de Sesión"),
                            ("LOGOUT", "Cierre de Sesión"),
                            ("VIEW", "Visualización"),
                            ("EXPORT", "Exportación"),
                            ("IMPORT", "Importación"),
                            ("VALIDATE", "Validación"),
                            ("REJECT", "Rechazo"),
                            ("APPROVE", "Aprobación"),
                            ("CANCEL", "Cancelación"),
                            ("RESTORE", "Restauración"),
                            ("ARCHIVE", "Archivado"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Acción",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Entidad",
                    ),
                ),
                ("module", models.CharField(max_length=100, verbose_name="Módulo")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Movimiento",
                "verbose_name_plural": "Plantillas de Movimientos",
                "db_table": "movement_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Creación"),
                            ("UPDATE", "Actualización"),
                            ("DELETE", "Eliminación"),
                            ("LOGIN", "Inicio de Sesión"),
                            ("LOGOUT", "Cierre de Sesión"),
                            ("VIEW", "Visualización"),
                            ("EXPORT", "Exportación"),
                            ("IMPORT", "Importación"),
                            ("VALIDATE", "Validación"),
                            ("REJECT", "Rechazo"),
                            ("APPROVE", "Aprobación"),
                            ("CANCEL", "Cancelación"),
                            ("RESTORE", "Restauración"),
                            ("ARCHIVE", "Archivado"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Acción",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descripción del Movimiento"),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Entidad",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de la Entidad",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID del Objeto"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Cambios Realizados"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Metadatos Adicionales"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de Sesión",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Módulo/Función",
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre de la Función",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tiempo de Ejecución (ms)"
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        default=True, verbose_name="Ejecutado Exitosamente"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, null=True, verbose_name="Etiquetas"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de Contenido",
                    ),
                ),
                (
                    "parent_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_movements",
                        to="audit.systemmovement",
                        verbose_name="Movimiento Padre",
                    ),
                ),
                (
                    "related_movements",
                    models.ManyToManyField(
                        blank=True,
                        to="audit.systemmovement",
                        verbose_name="Movimientos Relacionados",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento del Sistema",
                "verbose_name_plural": "Movimientos del Sistema",
                "db_table": "system_movements",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action_type"], name="system_move_action__e65614_idx"
                    ),
                    models.Index(
                        fields=["entity_type"], name="system_move_entity__b51be0_idx"
                    ),
                    models.Index(
                        fields=["user"], name="system_move_user_id_bc1335_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="system_move_timesta_d4e5d6_idx"
                    ),
                    models.Index(
                        fields=["module"], name="system_move_module_a4796b_idx"
                    ),
                    models.Index(
                        fields=["is_successful"], name="system_move_is_succ_31458f_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="system_move_priorit_1bc64e_idx"
                    ),
                ],
            },
        ),
    ]
