# Generated by Django 4.2.7 on 2025-08-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("VALIDADA", "Validada"),
                    ("PARCIALMENTE_SURTIDA", "Parcialmente Surtida"),
                    ("SURTIDA", "Surtida"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                max_length=25,
                verbose_name="Estado",
            ),
        ),
    ]
