# Generated by Django 4.2.7 on 2025-08-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_alter_receta_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="fecha_dispensacion_parcial",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Dispensación Parcial"
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="fecha_dispensacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Dispensación Completa"
            ),
        ),
    ]
