# Generated by Django 4.2.7 on 2025-08-16 20:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescriptions", "0003_receta_fecha_dispensacion_parcial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteDetalleReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_lote",
                    models.CharField(
                        help_text="Número identificador del lote",
                        max_length=100,
                        verbose_name="Número de Lote",
                    ),
                ),
                (
                    "fecha_caducidad",
                    models.DateField(verbose_name="Fecha de Caducidad"),
                ),
                (
                    "laboratorio",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Laboratorio/Fabricante",
                    ),
                ),
                (
                    "cantidad_dispensada",
                    models.PositiveIntegerField(
                        help_text="Cantidad específica dispensada de este lote",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad Dispensada de este Lote",
                    ),
                ),
                (
                    "fecha_dispensacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Dispensación del Lote"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones específicas de este lote",
                        null=True,
                        verbose_name="Observaciones del Lote",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "detalle_receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="prescriptions.detallereceta",
                        verbose_name="Detalle de Receta",
                    ),
                ),
                (
                    "dispensado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_dispensados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dispensado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Medicamento",
                "verbose_name_plural": "Lotes de Medicamentos",
                "db_table": "lote_detalle_recetas",
                "ordering": ["-fecha_dispensacion"],
                "indexes": [
                    models.Index(
                        fields=["numero_lote"], name="lote_detall_numero__50b885_idx"
                    ),
                    models.Index(
                        fields=["fecha_caducidad"],
                        name="lote_detall_fecha_c_2c2b1e_idx",
                    ),
                    models.Index(
                        fields=["laboratorio"], name="lote_detall_laborat_583a6f_idx"
                    ),
                ],
                "unique_together": {("detalle_receta", "numero_lote")},
            },
        ),
    ]
