# Generated by Django 4.2.7 on 2025-08-17 00:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescriptions", "0004_lotedetallereceta"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoMedicamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Clave única del medicamento (ej: PAR-500)",
                        max_length=20,
                        unique=True,
                        verbose_name="Clave del Medicamento",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo con concentración (ej: Paracetamol 500mg)",
                        max_length=200,
                        verbose_name="Nombre del Medicamento",
                    ),
                ),
                (
                    "principio_activo",
                    models.CharField(
                        help_text="Componente activo principal",
                        max_length=150,
                        verbose_name="Principio Activo",
                    ),
                ),
                (
                    "concentracion",
                    models.CharField(
                        help_text="Concentración del medicamento (ej: 500mg, 10ml)",
                        max_length=50,
                        verbose_name="Concentración",
                    ),
                ),
                (
                    "forma_farmaceutica",
                    models.CharField(
                        help_text="Tableta, jarabe, ampolleta, etc.",
                        max_length=50,
                        verbose_name="Forma Farmacéutica",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("ANALGESICO", "Analgésico"),
                            ("ANTIBIOTICO", "Antibiótico"),
                            ("ANTIINFLAMATORIO", "Antiinflamatorio"),
                            ("ANTIVIRAL", "Antiviral"),
                            ("CARDIOVASCULAR", "Cardiovascular"),
                            ("DERMATOLOGICO", "Dermatológico"),
                            ("ENDOCRINO", "Endócrino"),
                            ("GASTROINTESTINAL", "Gastrointestinal"),
                            ("GINECOLOGICO", "Ginecológico"),
                            ("HEMATOLOGICO", "Hematológico"),
                            ("IMMUNOLOGICO", "Inmunológico"),
                            ("NEUROLOGICO", "Neurológico"),
                            ("OFTALMOLOGICO", "Oftalmológico"),
                            ("ONCOLOGICO", "Oncológico"),
                            ("OTORRINOLARINGOLOGICO", "Otorrinolaringológico"),
                            ("PSIQUIATRICO", "Psiquiátrico"),
                            ("RESPIRATORIO", "Respiratorio"),
                            ("UROLOGICO", "Urológico"),
                            ("VACUNAS", "Vacunas"),
                            ("VITAMINAS_MINERALES", "Vitaminas y Minerales"),
                            ("OTROS", "Otros"),
                        ],
                        max_length=30,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tipo_receta_permitido",
                    models.CharField(
                        choices=[
                            ("FARMACIA", "Farmacia"),
                            ("CMI", "Centro de Mezclas (CMI)"),
                            ("AMBOS", "Ambos"),
                        ],
                        default="AMBOS",
                        max_length=10,
                        verbose_name="Tipo de Receta Permitido",
                    ),
                ),
                (
                    "via_administracion",
                    models.CharField(
                        blank=True,
                        help_text="Oral, intravenosa, intramuscular, tópica, etc.",
                        max_length=100,
                        verbose_name="Vía de Administración",
                    ),
                ),
                (
                    "dosis_sugerida",
                    models.CharField(
                        blank=True,
                        help_text="Dosis típica (ej: 1 tableta cada 8 horas)",
                        max_length=100,
                        verbose_name="Dosis Sugerida",
                    ),
                ),
                (
                    "contraindicaciones",
                    models.TextField(
                        blank=True,
                        help_text="Principales contraindicaciones",
                        verbose_name="Contraindicaciones",
                    ),
                ),
                (
                    "requiere_refrigeracion",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Refrigeración"
                    ),
                ),
                (
                    "es_controlado",
                    models.BooleanField(
                        default=False, verbose_name="Medicamento Controlado"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicamento del Catálogo",
                "verbose_name_plural": "Catálogo de Medicamentos",
                "db_table": "catalogo_medicamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="detallereceta",
            options={
                "verbose_name": "Detalle de Receta",
                "verbose_name_plural": "Detalles de Recetas",
            },
        ),
        migrations.RemoveIndex(
            model_name="detallereceta",
            name="detalle_rec_lote_e9b163_idx",
        ),
        migrations.RemoveIndex(
            model_name="detallereceta",
            name="detalle_rec_fecha_c_e971c7_idx",
        ),
        migrations.RemoveIndex(
            model_name="lotedetallereceta",
            name="lote_detall_numero__50b885_idx",
        ),
        migrations.RemoveIndex(
            model_name="lotedetallereceta",
            name="lote_detall_fecha_c_2c2b1e_idx",
        ),
        migrations.RemoveIndex(
            model_name="lotedetallereceta",
            name="lote_detall_laborat_583a6f_idx",
        ),
        migrations.RenameField(
            model_name="detallereceta",
            old_name="updated_at",
            new_name="fecha_actualizacion",
        ),
        migrations.RenameField(
            model_name="detallereceta",
            old_name="created_at",
            new_name="fecha_creacion",
        ),
        migrations.RenameField(
            model_name="receta",
            old_name="updated_at",
            new_name="fecha_actualizacion",
        ),
        migrations.AlterUniqueTogether(
            name="lotedetallereceta",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="detallereceta",
            name="observaciones_dispensacion",
            field=models.TextField(
                blank=True, verbose_name="Observaciones de Dispensación"
            ),
        ),
        migrations.AddField(
            model_name="lotedetallereceta",
            name="lote",
            field=models.CharField(
                default="SIN_LOTE", max_length=50, verbose_name="Número de Lote"
            ),
        ),
        migrations.AlterField(
            model_name="detallereceta",
            name="clave_medicamento",
            field=models.CharField(max_length=50, verbose_name="Clave del Medicamento"),
        ),
        migrations.AlterField(
            model_name="detallereceta",
            name="dosis",
            field=models.CharField(
                help_text="Cantidad y frecuencia (ej: 1 tableta cada 8 horas)",
                max_length=200,
                verbose_name="Dosis",
            ),
        ),
        migrations.AlterField(
            model_name="lotedetallereceta",
            name="cantidad_dispensada",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad Dispensada",
            ),
        ),
        migrations.AlterField(
            model_name="lotedetallereceta",
            name="dispensado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dispensado por",
            ),
        ),
        migrations.AlterField(
            model_name="lotedetallereceta",
            name="fecha_dispensacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Dispensación"
            ),
        ),
        migrations.AlterField(
            model_name="lotedetallereceta",
            name="observaciones",
            field=models.TextField(
                blank=True, default="", verbose_name="Observaciones"
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="fecha_dispensacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Dispensación"
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="indicaciones_generales",
            field=models.TextField(
                blank=True,
                help_text="Instrucciones generales para el paciente",
                verbose_name="Indicaciones Generales",
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="observaciones",
            field=models.TextField(
                blank=True,
                help_text="Observaciones adicionales de validación o dispensación",
                verbose_name="Observaciones",
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="prescrito_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recetas_prescritas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prescrito por",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="detallereceta",
            unique_together={("receta", "clave_medicamento")},
        ),
        migrations.AddIndex(
            model_name="detallereceta",
            index=models.Index(
                fields=["cantidad_surtida"], name="detalle_rec_cantida_ad7b48_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="lotedetallereceta",
            table="lotes_detalle_receta",
        ),
        migrations.AddIndex(
            model_name="catalogomedicamentos",
            index=models.Index(fields=["clave"], name="catalogo_me_clave_3b8514_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogomedicamentos",
            index=models.Index(fields=["nombre"], name="catalogo_me_nombre_e932ab_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogomedicamentos",
            index=models.Index(
                fields=["principio_activo"], name="catalogo_me_princip_d837ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogomedicamentos",
            index=models.Index(
                fields=["categoria"], name="catalogo_me_categor_cf1890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogomedicamentos",
            index=models.Index(fields=["activo"], name="catalogo_me_activo_f95508_idx"),
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="concentracion",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="duracion_tratamiento",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="forma_farmaceutica",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="frecuencia",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="laboratorio",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="medicamento_sustituido",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="observaciones",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="permite_sustitucion",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="precio_unitario",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="unidad_medida",
        ),
        migrations.RemoveField(
            model_name="detallereceta",
            name="via_administracion",
        ),
        migrations.RemoveField(
            model_name="lotedetallereceta",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="lotedetallereceta",
            name="laboratorio",
        ),
        migrations.RemoveField(
            model_name="lotedetallereceta",
            name="numero_lote",
        ),
        migrations.RemoveField(
            model_name="lotedetallereceta",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="detallereceta",
            name="medicamento_catalogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prescriptions.catalogomedicamentos",
                verbose_name="Medicamento del Catálogo",
            ),
        ),
    ]
