# Generated by Django 4.2.7 on 2025-08-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20250824_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ipblacklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ipwhitelist',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='PasswordPolicy',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='SecuritySettings',
        ),
        migrations.RemoveField(
            model_name='twofactorsecret',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersecurityprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActiveSession',
        ),
        migrations.DeleteModel(
            name='IPBlacklist',
        ),
        migrations.DeleteModel(
            name='IPWhitelist',
        ),
        migrations.DeleteModel(
            name='SecurityLog',
        ),
        migrations.DeleteModel(
            name='TwoFactorSecret',
        ),
        migrations.DeleteModel(
            name='UserSecurityProfile',
        ),
    ]
