# Generated by Django 4.2.7 on 2025-08-16 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('expediente', models.CharField(help_text='Identificador único del paciente', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El expediente debe contener solo letras mayúsculas, números y guiones', regex='^[A-Z0-9-]+$')], verbose_name='Número de Expediente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CURP inválida. Formato: 4 letras, 6 números, H/M, 5 letras, 2 números', regex='^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9]{2}$')], verbose_name='CURP')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('patologia', models.CharField(max_length=200, verbose_name='Patología Principal')),
                ('cie10', models.CharField(help_text='Clasificación Internacional de Enfermedades', max_length=10, verbose_name='Código CIE-10')),
                ('fecha_diagnostico', models.DateField(verbose_name='Fecha de Diagnóstico')),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('ND', 'No Determinado')], default='ND', max_length=3, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias Conocidas')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Contacto de Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del Contacto de Emergencia')),
                ('numero_seguro_social', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Seguro Social')),
                ('institucion_seguro', models.CharField(blank=True, help_text='IMSS, ISSSTE, Seguro Popular, etc.', max_length=100, null=True, verbose_name='Institución de Seguro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
                'indexes': [models.Index(fields=['curp'], name='pacientes_curp_a9f645_idx'), models.Index(fields=['nombre', 'apellido_paterno'], name='pacientes_nombre_88163e_idx'), models.Index(fields=['fecha_nacimiento'], name='pacientes_fecha_n_206599_idx'), models.Index(fields=['created_at'], name='pacientes_created_2b2633_idx')],
            },
        ),
    ]
