# Generated by Django 4.2.7 on 2025-08-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIE10Mexico",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        help_text="Código oficial CIE-10 (ej: A00.0, B15.9, etc.)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código CIE-10",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción completa del diagnóstico",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "descripcion_corta",
                    models.CharField(
                        blank=True,
                        help_text="Versión abreviada de la descripción",
                        max_length=200,
                        null=True,
                        verbose_name="Descripción Corta",
                    ),
                ),
                (
                    "capitulo",
                    models.CharField(
                        help_text="Capítulo del CIE-10 (I-XXII)",
                        max_length=5,
                        verbose_name="Capítulo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoría del código (primeros 3 caracteres)",
                        max_length=10,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENFERMEDAD", "Enfermedad"),
                            ("TRAUMATISMO", "Traumatismo y envenenamiento"),
                            ("FACTOR_EXTERNO", "Causas externas"),
                            (
                                "FACTOR_SALUD",
                                "Factores que influyen en el estado de salud",
                            ),
                        ],
                        max_length=20,
                        verbose_name="Tipo de código",
                    ),
                ),
                (
                    "genero_aplicable",
                    models.CharField(
                        choices=[
                            ("AMBOS", "Ambos géneros"),
                            ("MASCULINO", "Solo masculino"),
                            ("FEMENINO", "Solo femenino"),
                        ],
                        default="AMBOS",
                        max_length=10,
                        verbose_name="Género aplicable",
                    ),
                ),
                (
                    "edad_minima",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Edad mínima en años para aplicar este diagnóstico",
                        null=True,
                        verbose_name="Edad mínima",
                    ),
                ),
                (
                    "edad_maxima",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Edad máxima en años para aplicar este diagnóstico",
                        null=True,
                        verbose_name="Edad máxima",
                    ),
                ),
                (
                    "es_mortalidad",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este código puede ser causa básica de muerte",
                        verbose_name="Es causa de mortalidad",
                    ),
                ),
                (
                    "es_morbilidad",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este código puede usarse para morbilidad",
                        verbose_name="Es causa de morbilidad",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "CIE-10 México",
                "verbose_name_plural": "CIE-10 México",
                "db_table": "cie10_mexico",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="cie10_mexic_codigo_dd73ec_idx"
                    ),
                    models.Index(
                        fields=["categoria"], name="cie10_mexic_categor_5f4771_idx"
                    ),
                    models.Index(
                        fields=["capitulo"], name="cie10_mexic_capitul_f4359d_idx"
                    ),
                    models.Index(fields=["tipo"], name="cie10_mexic_tipo_d0c0f6_idx"),
                    models.Index(
                        fields=["descripcion"], name="cie10_mexic_descrip_2fd187_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="cie10_oficial",
            field=models.ForeignKey(
                blank=True,
                help_text="Relación con el catálogo oficial CIE-10 México",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.cie10mexico",
                verbose_name="CIE-10 Oficial",
            ),
        ),
    ]
