# Generated by Django 4.2.7 on 2025-08-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_update_patient_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cie10mexico",
            name="edad_maxima",
        ),
        migrations.RemoveField(
            model_name="cie10mexico",
            name="edad_minima",
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="af_prin",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="AF_PRIN"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="asterisco",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Asterisco"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="birmm",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="BIRMM"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="causa_type",
            field=models.TextField(blank=True, null=True, verbose_name="Tipo de causa"),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="cbd",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="CBD"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="clave_capitulo",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Clave capítulo"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="clave_programa_sis",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Clave programa SIS"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="cod_adi_mort",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Código adicional mortalidad",
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="cod_complemen_morbi",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Código complemento morbilidad",
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="cod_sit_lesion",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Código situación lesión",
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="codigox",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Código X"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="consecutivo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Consecutivo"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="cve_causa_type",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Clave tipo causa"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="cve_maternas_seed_epid",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Clave maternas SEED EPID",
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="daga",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="DAGA"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="def_fetal_cbd",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="DEF_FETAL_CBD"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="def_fetal_cm",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="DEF_FETAL_CM"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="def_maternas",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="DEF_MATERNAS"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="descripcion_mm_grupo",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Descripción grupo MM",
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="descripcion_mm_subgrupo",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Descripción subgrupo MM",
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="descripcion_sinac_grupo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción grupo SINAC"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="descripcion_sinac_subgrupo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción subgrupo SINAC"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="dia_fetal",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Día fetal"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="dia_sis",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Día SIS"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="edas_e_iras_en_m5",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="EDAS_E_IRAS_EN_M5"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="epi_clave",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="EPI_CLAVE"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="epi_clave_desc",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción EPI_CLAVE"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="epi_morb",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="EPI_MORB"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="epi_morta",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="EPI_MORTA"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="epi_morta_m5",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="EPI_MORTA_M5"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="erradicado",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Erradicado"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="es_causes",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ES_CAUSES"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="es_suive_est_brote",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ES_SUIVE_EST_BROTE"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="es_suive_est_epi",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ES_SUIVE_EST_EPI"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="es_suive_morb",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ES_SUIVE_MORB"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="es_suive_morta",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ES_SUIVE_MORTA"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="es_suive_notin",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ES_SUIVE_NOTIN"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="grupo1",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Grupo 1"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="letra",
            field=models.CharField(
                blank=True, max_length=1, null=True, verbose_name="Letra del código"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lgbd165",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="LGBD165"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lgbd190",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="LGBD190"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="linf",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="LINF"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lista1",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Lista 1"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lista5",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Lista 5"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lm_morbi",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="LM_MORBI"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lm_morta",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="LM_MORTA"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lomsbeck",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="LOMSBECK"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lsex",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="LSEX"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="lsup",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="LSUP"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="n_inter",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="N_INTER"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="nin",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="NIN"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="ninmtobs",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="NINMTOBS"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="no_aph",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="NO_APH"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="no_caracteres",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de caracteres"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="no_cbd",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="NO_CBD"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="nombre_capitulo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nombre del capítulo"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="notdiaria",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Notificación diaria"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="notsemanal",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Notificación semanal",
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="num_causes",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número de causas"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="prin_mm",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PRIN_MM"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="prin_mm_grupo",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PRIN_MM_GRUPO"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="prin_mm_subgrupo",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PRIN_MM_SUBGRUPO"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="prin_sinac",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PRIN_SINAC"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="prin_sinac_grupo",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PRIN_SINAC_GRUPO"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="prin_sinac_subgrupo",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PRIN_SINAC_SUBGRUPO"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="prinmorb",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PRINMORB"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="prinmorta",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PRINMORTA"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="rubrica_type",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Tipo de rúbrica"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="sinac",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="SINAC"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="sistema_especial",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Sistema especial"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="trivial",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Trivial"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="valid",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Válido"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="year_aplicacion",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Año aplicación"
            ),
        ),
        migrations.AddField(
            model_name="cie10mexico",
            name="year_modifi",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Año modificación"
            ),
        ),
    ]
