# Generated by Django 4.2.7 on 2025-08-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=20, unique=True)),
                ("min_length", models.IntegerField(default=8)),
                ("require_uppercase", models.BooleanField(default=True)),
                ("require_lowercase", models.BooleanField(default=True)),
                ("require_numbers", models.BooleanField(default=True)),
                ("require_symbols", models.BooleanField(default=True)),
                ("max_age_days", models.IntegerField(default=90)),
                ("history_count", models.IntegerField(default=5)),
            ],
            options={
                "verbose_name": "Política de Contraseñas",
                "verbose_name_plural": "Políticas de Contraseñas",
            },
        ),
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_password_length", models.IntegerField(default=8)),
                ("require_uppercase", models.BooleanField(default=True)),
                ("require_lowercase", models.BooleanField(default=True)),
                ("require_numbers", models.BooleanField(default=True)),
                ("require_symbols", models.BooleanField(default=True)),
                ("password_history_count", models.IntegerField(default=5)),
                ("password_expiry_days", models.IntegerField(default=90)),
                ("max_login_attempts", models.IntegerField(default=5)),
                ("lockout_duration_minutes", models.IntegerField(default=30)),
                ("max_concurrent_sessions", models.IntegerField(default=3)),
                ("session_timeout_minutes", models.IntegerField(default=480)),
                ("require_2fa_for_roles", models.JSONField(default=list)),
                ("enable_ip_whitelist", models.BooleanField(default=False)),
                ("allowed_ip_ranges", models.JSONField(default=list)),
                ("blocked_ips", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Seguridad",
                "verbose_name_plural": "Configuraciones de Seguridad",
            },
        ),
        migrations.CreateModel(
            name="UserSecurityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("backup_tokens", models.JSONField(default=list)),
                ("password_history", models.JSONField(default=list)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("force_password_change", models.BooleanField(default=False)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_successful_login", models.DateTimeField(blank=True, null=True)),
                ("security_questions", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Seguridad",
                "verbose_name_plural": "Perfiles de Seguridad",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret_key", models.CharField(max_length=32)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_secret",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Secreto 2FA",
                "verbose_name_plural": "Secretos 2FA",
            },
        ),
        migrations.CreateModel(
            name="IPWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("ip_range", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Lista Blanca",
                "verbose_name_plural": "IPs Lista Blanca",
            },
        ),
        migrations.CreateModel(
            name="IPBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("reason", models.CharField(max_length=200)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("is_permanent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Lista Negra",
                "verbose_name_plural": "IPs Lista Negra",
            },
        ),
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Exitoso"),
                            ("LOGIN_FAILED", "Login Fallido"),
                            ("LOGIN_BLOCKED", "Login Bloqueado"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGED", "Contraseña Cambiada"),
                            ("2FA_ENABLED", "2FA Habilitado"),
                            ("2FA_DISABLED", "2FA Deshabilitado"),
                            ("2FA_SUCCESS", "2FA Exitoso"),
                            ("2FA_FAILED", "2FA Fallido"),
                            ("ACCOUNT_LOCKED", "Cuenta Bloqueada"),
                            ("ACCOUNT_UNLOCKED", "Cuenta Desbloqueada"),
                            ("PERMISSION_DENIED", "Permiso Denegado"),
                            ("SUSPICIOUS_ACTIVITY", "Actividad Sospechosa"),
                            ("IP_BLOCKED", "IP Bloqueada"),
                            ("MULTIPLE_SESSIONS", "Múltiples Sesiones"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Bajo"),
                            ("MEDIUM", "Medio"),
                            ("HIGH", "Alto"),
                            ("CRITICAL", "Crítico"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Seguridad",
                "verbose_name_plural": "Logs de Seguridad",
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="authenticat_timesta_8818b3_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="authenticat_event_t_0c7d52_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="authenticat_user_id_51b981_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="authenticat_severit_03def6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_info", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión Activa",
                "verbose_name_plural": "Sesiones Activas",
                "indexes": [
                    models.Index(
                        fields=["user", "-last_activity"],
                        name="authenticat_user_id_636580_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_fb7ad4_idx"
                    ),
                ],
            },
        ),
    ]
