# Generated by Django 4.2.7 on 2025-08-16 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Métrica"
                    ),
                ),
                (
                    "metric_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="Valor"
                    ),
                ),
                (
                    "metric_unit",
                    models.CharField(
                        default="count", max_length=50, verbose_name="Unidad"
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Categoría"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="Metadatos")),
            ],
            options={
                "verbose_name": "Métrica del Sistema",
                "verbose_name_plural": "Métricas del Sistema",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "timestamp"],
                        name="reports_sys_metric__60c5b1_idx",
                    ),
                    models.Index(
                        fields=["category", "timestamp"],
                        name="reports_sys_categor_ee7b3b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del Reporte"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Reporte Diario"),
                            ("WEEKLY", "Reporte Semanal"),
                            ("MONTHLY", "Reporte Mensual"),
                            ("CUSTOM", "Reporte Personalizado"),
                            ("PERFORMANCE", "Reporte de Rendimiento"),
                            ("INVENTORY", "Reporte de Inventario"),
                            ("AUDIT", "Reporte de Auditoría"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "query_template",
                    models.JSONField(verbose_name="Plantilla de Consulta"),
                ),
                (
                    "visualization_config",
                    models.JSONField(
                        default=dict, verbose_name="Configuración de Visualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Reporte",
                "verbose_name_plural": "Plantillas de Reportes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Título del Reporte"),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Parámetros"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Datos del Reporte"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Ruta del Archivo",
                    ),
                ),
                ("date_from", models.DateTimeField(verbose_name="Fecha Desde")),
                ("date_to", models.DateTimeField(verbose_name="Fecha Hasta")),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generado por",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reporttemplate",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Generado",
                "verbose_name_plural": "Reportes Generados",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Crear"),
                            ("UPDATE", "Actualizar"),
                            ("DELETE", "Eliminar"),
                            ("VIEW", "Ver"),
                            ("LOGIN", "Iniciar Sesión"),
                            ("LOGOUT", "Cerrar Sesión"),
                            ("DISPENSE", "Dispensar"),
                            ("VALIDATE", "Validar"),
                            ("CANCEL", "Cancelar"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID del Objeto",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        max_length=300, verbose_name="Representación del Objeto"
                    ),
                ),
                ("changes", models.JSONField(default=dict, verbose_name="Cambios")),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Dirección IP"),
                ),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Clave de Sesión",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="reports_aud_user_id_7a10fa_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="reports_aud_action_6c25e2_idx",
                    ),
                    models.Index(
                        fields=["model_name", "timestamp"],
                        name="reports_aud_model_n_4d408c_idx",
                    ),
                ],
            },
        ),
    ]
